// lib/mock-data.ts — Static mock data for all pages

export const DEALERS = [
  {
    id: "1",
    shopName: "Sri Ram Cement Depot",
    area: "RS Puram",
    rating: 4.8,
    reviewCount: 124,
    isVerified: true,
    categories: ["Cement", "Sand"],
    phone: "98765 43210",
    materials: [
      { name: "Ultratech OPC 53 Grade", price: "₹390/bag", inStock: true },
      { name: "Dalmia PPC Cement", price: "₹370/bag", inStock: true },
      { name: "River Sand", price: "₹1,800/tonne", inStock: false },
    ],
  },
  {
    id: "2",
    shopName: "Murugan Steel Traders",
    area: "Gandhipuram",
    rating: 4.6,
    reviewCount: 89,
    isVerified: true,
    categories: ["TMT Steel"],
    phone: "97654 32109",
    materials: [
      { name: "JSW TMT Fe500", price: "₹59,500/tonne", inStock: true },
      { name: "TATA Tiscon Fe500D", price: "₹61,000/tonne", inStock: true },
      { name: "Vizag Steel TMT", price: "₹58,000/tonne", inStock: true },
    ],
  },
  {
    id: "3",
    shopName: "Coimbatore Bricks & Aggregates",
    area: "Singanallur",
    rating: 4.3,
    reviewCount: 56,
    isVerified: false,
    categories: ["Bricks", "Aggregates", "Sand"],
    phone: "95432 10987",
    materials: [
      { name: "Country Bricks (1st quality)", price: "₹4,800/1000 pcs", inStock: true },
      { name: "20mm Aggregate", price: "₹1,300/tonne", inStock: true },
      { name: "M-Sand", price: "₹1,500/tonne", inStock: true },
    ],
  },
  {
    id: "4",
    shopName: "Lakshmi Paint & Hardware",
    area: "Peelamedu",
    rating: 4.5,
    reviewCount: 201,
    isVerified: true,
    categories: ["Paint", "Tiles", "Hardware"],
    phone: "94321 09876",
    materials: [
      { name: "Asian Paints Apex Exterior", price: "₹320/litre", inStock: true },
      { name: "Kajaria Floor Tiles 600x600", price: "₹85/sq.ft", inStock: true },
      { name: "Berger WeatherCoat", price: "₹290/litre", inStock: false },
    ],
  },
  {
    id: "5",
    shopName: "Vel Electrical Stores",
    area: "Saibaba Colony",
    rating: 4.7,
    reviewCount: 143,
    isVerified: true,
    categories: ["Electrical", "Plumbing"],
    phone: "93210 98765",
    materials: [
      { name: "Havells 2.5mm Wire (90m)", price: "₹2,200/roll", inStock: true },
      { name: "Finolex PVC Pipe 1\"", price: "₹380/piece", inStock: true },
      { name: "Legrand Switch Plate", price: "₹450/unit", inStock: true },
    ],
  },
];

export const BUILDERS = [
  {
    id: "1",
    companyName: "Shree Constructions",
    ownerName: "Rajesh Kumar",
    type: "Builder",
    area: "RS Puram",
    experience: 15,
    rating: 4.9,
    reviewCount: 87,
    isVerified: true,
    phone: "98765 11223",
    description: "Specialising in residential villas and apartments. 200+ projects delivered across Coimbatore with on-time completion guarantee.",
    tags: ["Villas", "Apartments", "Renovation"],
    projects: [
      { title: "Greenfield Villa, Peelamedu", year: 2023, sqft: 2400 },
      { title: "Sky Apartments, RS Puram", year: 2022, sqft: 12000 },
    ],
  },
  {
    id: "2",
    companyName: "Design Arc Studio",
    ownerName: "Priya Suresh",
    type: "Architect",
    area: "Race Course",
    experience: 10,
    rating: 4.8,
    reviewCount: 63,
    isVerified: true,
    phone: "97654 22334",
    description: "Award-winning architecture firm focused on modern, sustainable design. From concept to completion.",
    tags: ["Modern", "Sustainable", "Commercial"],
    projects: [
      { title: "Eco Home, Vadavalli", year: 2023, sqft: 1800 },
      { title: "Retail Hub, Gandhipuram", year: 2022, sqft: 5500 },
    ],
  },
  {
    id: "3",
    companyName: "AK Civil Works",
    ownerName: "Anand Krishnamurthy",
    type: "Contractor",
    area: "Singanallur",
    experience: 8,
    rating: 4.4,
    reviewCount: 41,
    isVerified: true,
    phone: "94321 33445",
    description: "Civil contractor for residential construction, compound walls, flooring, and interior finishing works.",
    tags: ["Civil Works", "Flooring", "Finishing"],
    projects: [
      { title: "Row Houses, Sulur", year: 2023, sqft: 6000 },
      { title: "Individual Villa, Kalapatti", year: 2023, sqft: 2200 },
    ],
  },
  {
    id: "4",
    companyName: "Vega Interiors",
    ownerName: "Meena Ravi",
    type: "Architect",
    area: "Peelamedu",
    experience: 12,
    rating: 4.7,
    reviewCount: 95,
    isVerified: true,
    phone: "93210 44556",
    description: "Interior design and architecture studio. Turnkey interior solutions for homes, offices, and retail spaces.",
    tags: ["Interior", "Turnkey", "Office"],
    projects: [
      { title: "Tech Office, Peelamedu", year: 2024, sqft: 3200 },
      { title: "Luxury Flat Interior, Race Course", year: 2023, sqft: 1600 },
    ],
  },
];

export const PROPERTIES = [
  {
    id: "1",
    title: "3BHK Apartment — Peelamedu",
    type: "SELL",
    price: 6500000,
    area: 1450,
    bedrooms: 3,
    bathrooms: 2,
    location: "Peelamedu, Coimbatore",
    postedBy: "Suresh R",
    daysAgo: 2,
    tag: "New",
  },
  {
    id: "2",
    title: "2BHK Flat for Rent — RS Puram",
    type: "RENT",
    price: 14000,
    area: 1050,
    bedrooms: 2,
    bathrooms: 2,
    location: "RS Puram, Coimbatore",
    postedBy: "Kavitha M",
    daysAgo: 1,
    tag: "Hot",
  },
  {
    id: "3",
    title: "Commercial Land — Sulur",
    type: "SELL",
    price: 2200000,
    area: 3600,
    bedrooms: null,
    bathrooms: null,
    location: "Sulur, Coimbatore",
    postedBy: "Bala K",
    daysAgo: 5,
    tag: null,
  },
  {
    id: "4",
    title: "Independent House — Saibaba Colony",
    type: "SELL",
    price: 9800000,
    area: 2200,
    bedrooms: 4,
    bathrooms: 3,
    location: "Saibaba Colony, Coimbatore",
    postedBy: "Anita S",
    daysAgo: 3,
    tag: null,
  },
  {
    id: "5",
    title: "1BHK Furnished Flat — Gandhipuram",
    type: "RENT",
    price: 8500,
    area: 650,
    bedrooms: 1,
    bathrooms: 1,
    location: "Gandhipuram, Coimbatore",
    postedBy: "Ravi T",
    daysAgo: 7,
    tag: null,
  },
  {
    id: "6",
    title: "Residential Plot — Kalapatti",
    type: "SELL",
    price: 3500000,
    area: 2400,
    bedrooms: null,
    bathrooms: null,
    location: "Kalapatti, Coimbatore",
    postedBy: "Mani P",
    daysAgo: 10,
    tag: null,
  },
];

export const MATERIAL_CATEGORIES = [
  { key: "CEMENT", label: "Cement", emoji: "🏗️" },
  { key: "TMT_STEEL", label: "TMT Steel", emoji: "🔩" },
  { key: "BRICKS", label: "Bricks", emoji: "🧱" },
  { key: "SAND", label: "Sand", emoji: "⛱️" },
  { key: "AGGREGATES", label: "Aggregates", emoji: "🪨" },
  { key: "PAINT", label: "Paint", emoji: "🎨" },
  { key: "TILES", label: "Tiles", emoji: "◼️" },
  { key: "PLUMBING", label: "Plumbing", emoji: "🔧" },
  { key: "ELECTRICAL", label: "Electrical", emoji: "⚡" },
  { key: "WOOD", label: "Wood", emoji: "🪵" },
];

export const AREAS = [
  "All Areas", "RS Puram", "Gandhipuram", "Peelamedu",
  "Saibaba Colony", "Race Course", "Singanallur",
  "Ganapathy", "Vadavalli", "Kalapatti", "Sulur",
];

export function formatPrice(price: number, type?: string): string {
  if (type === "RENT") return `₹${price.toLocaleString()}/mo`;
  if (price >= 10000000) return `₹${(price / 10000000).toFixed(1)} Cr`;
  if (price >= 100000) return `₹${(price / 100000).toFixed(1)} L`;
  return `₹${price.toLocaleString()}`;
}
